
mybatis:
#  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

    # 每次查询从数据库取的记录数
    default-fetch-size: 100
    default-statement-timeout: 30

pagehelper:

  # 方言
  helperDialect: MariaDB

  # 分页参数合理化，超过当前页会调整为第一页
  # reasonable: true

  # 支持通过 Mapper 接口参数来传递分页参数，默认值false
  # 分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true

  # params：为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  # 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为 pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSize=pageSize
  params: count=countSql
